### ISSUE TITLE
编译没有问题，运行安装到模拟器出现这个问题，明天用真机试试看

### ISSUE THREAD

**Issue by llllIIIllll** [leavesCZY/compose_chat#1]
Unable to determine application id: com.android.tools.idea.run.ApkProvisionException: Error loading build artifacts from: 
{
  "version": 3,
  "artifactType": {
    "type": "APK",
    "kind": "Directory"
  },
  "applicationId": "github.leavesc.compose_chat",
  "variantName": "debug",
  "elements": [
    {
      "type": "SINGLE",
      "filters": [],
      "attributes": [],
      "versionCode": 1,
      "versionName": "1.0",
      "outputFile": "chat_debug_versionCode_1_versionName_1.0_2021_08_02_16_59_09.apk"
    }
  ],
  "elementType": "File"
}

**Comment by leavesCZY** [comment]
可以尝试使用 Arctic Fox 2020.3.1 版本进行编译
