### ISSUE TITLE
最新代码 编译报错   上个版本还是可以的  求工程配置  包括jdk等等版本

### ISSUE THREAD

**Issue by xiaoxing1992** [leavesCZY/compose_chat#6]
ComposeComponentRegistrar has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0

**Comment by leavesCZY** [comment]
@xiaoxing1992 这个是由于我将 kotlinCompilerExtensionVersion 升级到 1.4.5 导致的，此版本要求 JDK 构建版本必须是 Java 17+。建议将 Android Studio 升级到 Flamingo 正式版，然后切换 JDK 版本即可

![](https://user-images.githubusercontent.com/30774063/232475495-fee45b2c-1565-40b2-83d4-c4bcb7145acb.png)

**Comment by leavesCZY** [comment]
关于 kotlinCompilerExtensionVersion，可以看这里：https://developer.android.com/jetpack/androidx/releases/compose-compiler?hl=en#version_145_3
